using LeagueManager.Application.Interfaces;
using LeagueManager.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace LeagueManager.Persistence.EntityFramework
{
    public class LeagueManagerDbContext : DbContext, ILeagueManagerDbContext
    {
        private readonly IImageFileLoader imageFileLoader;

        public LeagueManagerDbContext(
            DbContextOptions<LeagueManagerDbContext> options,
            IImageFileLoader imageFileLoader)
            : base(options)
        {
            this.imageFileLoader = imageFileLoader;
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TeamMatch>();
            modelBuilder.Entity<IntegerScore>();
            modelBuilder.Entity<Country>().HasData(
                SeedCountries()
            );
            modelBuilder.Entity<Team>();

            modelBuilder.ApplyConfigurationsFromAssembly(typeof(LeagueManagerDbContext).Assembly);
        }

        public DbSet<Country> Countries { get; set; }
        public DbSet<TeamLeague> Leagues { get; set; }
        public DbSet<Player> Players { get; set; }
        public DbSet<Team> Teams { get; set; }

        //Got countries from https://datahub.io/core/country-codes
        private IEnumerable<Country> SeedCountries()
        {
            return new Country[]
            {
                new Country { Id = 1, Name = "Taiwan", Code = "TPE" },
                new Country { Id = 2, Name = "Afghanistan", Code = "AFG" },
                new Country { Id = 3, Name = "Albania", Code = "ALB" },
                new Country { Id = 4, Name = "Algeria", Code = "ALG" },
                new Country { Id = 5, Name = "American Samoa", Code = "ASA" },
                new Country { Id = 6, Name = "Andorra", Code = "AND" },
                new Country { Id = 7, Name = "Angola", Code = "ANG" },
                new Country { Id = 8, Name = "Anguilla", Code = "AIA" },
                new Country { Id = 9, Name = "Antarctica", Code = "ROS" },
                new Country { Id = 10, Name = "Antigua & Barbuda", Code = "ATG" },
                new Country { Id = 11, Name = "Argentina", Code = "ARG" },
                new Country { Id = 12, Name = "Armenia", Code = "ARM" },
                new Country { Id = 13, Name = "Aruba", Code = "ARU" },
                new Country { Id = 14, Name = "Australia", Code = "AUS" },
                new Country { Id = 15, Name = "Austria", Code = "AUT" },
                new Country { Id = 16, Name = "Azerbaijan", Code = "AZE" },
                new Country { Id = 17, Name = "Bahamas", Code = "BAH" },
                new Country { Id = 18, Name = "Bahrain", Code = "BHR" },
                new Country { Id = 19, Name = "Bangladesh", Code = "BAN" },
                new Country { Id = 20, Name = "Barbados", Code = "BRB" },
                new Country { Id = 21, Name = "Belarus", Code = "BLR" },
                new Country { Id = 22, Name = "Belgium", Code = "BEL" },
                new Country { Id = 23, Name = "Belize", Code = "BLZ" },
                new Country { Id = 24, Name = "Benin", Code = "BEN" },
                new Country { Id = 25, Name = "Bermuda", Code = "BER" },
                new Country { Id = 26, Name = "Bhutan", Code = "BHU" },
                new Country { Id = 27, Name = "Bolivia", Code = "BOL" },
                new Country { Id = 28, Name = "Caribbean Netherlands", Code = "ANT" },
                new Country { Id = 29, Name = "Bosnia", Code = "BIH" },
                new Country { Id = 30, Name = "Botswana", Code = "BOT" },
                new Country { Id = 31, Name = "Bouvet Island", Code = "" },
                new Country { Id = 32, Name = "Brazil", Code = "BRA" },
                new Country { Id = 33, Name = "British Indian Ocean Territory", Code = "" },
                new Country { Id = 34, Name = "British Virgin Islands", Code = "VGB" },
                new Country { Id = 35, Name = "Brunei", Code = "BRU" },
                new Country { Id = 36, Name = "Bulgaria", Code = "BUL" },
                new Country { Id = 37, Name = "Burkina Faso", Code = "BFA" },
                new Country { Id = 38, Name = "Burundi", Code = "BDI" },
                new Country { Id = 39, Name = "Cape Verde", Code = "CPV" },
                new Country { Id = 40, Name = "Cambodia", Code = "CAM" },
                new Country { Id = 41, Name = "Cameroon", Code = "CMR" },
                new Country { Id = 42, Name = "Canada", Code = "CAN" },
                new Country { Id = 43, Name = "Cayman Islands", Code = "CAY" },
                new Country { Id = 44, Name = "Central African Republic", Code = "CTA" },
                new Country { Id = 45, Name = "Chad", Code = "CHA" },
                new Country { Id = 46, Name = "Chile", Code = "CHI" },
                new Country { Id = 47, Name = "China", Code = "CHN" },
                new Country { Id = 48, Name = "Hong Kong", Code = "HKG" },
                new Country { Id = 49, Name = "Macau", Code = "MAC" },
                new Country { Id = 50, Name = "Christmas Island", Code = "CXR" },
                new Country { Id = 51, Name = "Cocos (Keeling) Islands", Code = "CCK" },
                new Country { Id = 52, Name = "Colombia", Code = "COL" },
                new Country { Id = 53, Name = "Comoros", Code = "COM" },
                new Country { Id = 54, Name = "Congo - Brazzaville", Code = "CGO" },
                new Country { Id = 55, Name = "Cook Islands", Code = "COK" },
                new Country { Id = 56, Name = "Costa Rica", Code = "CRC" },
                new Country { Id = 57, Name = "Croatia", Code = "CRO" },
                new Country { Id = 58, Name = "Cuba", Code = "CUB" },
                new Country { Id = 59, Name = "Curaçao", Code = "" },
                new Country { Id = 60, Name = "Cyprus", Code = "CYP" },
                new Country { Id = 61, Name = "Czechia", Code = "CZE" },
                new Country { Id = 62, Name = "Côte d’Ivoire", Code = "CIV" },
                new Country { Id = 63, Name = "North Korea", Code = "PRK" },
                new Country { Id = 64, Name = "Congo - Kinshasa", Code = "COD" },
                new Country { Id = 65, Name = "Denmark", Code = "DEN" },
                new Country { Id = 66, Name = "Djibouti", Code = "DJI" },
                new Country { Id = 67, Name = "Dominica", Code = "DMA" },
                new Country { Id = 68, Name = "Dominican Republic", Code = "DOM" },
                new Country { Id = 69, Name = "Ecuador", Code = "ECU" },
                new Country { Id = 70, Name = "Egypt", Code = "EGY" },
                new Country { Id = 71, Name = "El Salvador", Code = "SLV" },
                new Country { Id = 72, Name = "Equatorial Guinea", Code = "EQG" },
                new Country { Id = 73, Name = "Eritrea", Code = "ERI" },
                new Country { Id = 74, Name = "Estonia", Code = "EST" },
                new Country { Id = 75, Name = "Ethiopia", Code = "ETH" },
                new Country { Id = 76, Name = "Falkland Islands", Code = "FLK" },
                new Country { Id = 77, Name = "Faroe Islands", Code = "FRO" },
                new Country { Id = 78, Name = "Fiji", Code = "FIJ" },
                new Country { Id = 79, Name = "Finland", Code = "FIN" },
                new Country { Id = 80, Name = "France", Code = "FRA" },
                new Country { Id = 81, Name = "French Guiana", Code = "GUF" },
                new Country { Id = 82, Name = "French Polynesia", Code = "TAH" },
                new Country { Id = 83, Name = "French Southern Territories", Code = "" },
                new Country { Id = 84, Name = "Gabon", Code = "GAB" },
                new Country { Id = 85, Name = "Gambia", Code = "GAM" },
                new Country { Id = 86, Name = "Georgia", Code = "GEO" },
                new Country { Id = 87, Name = "Germany", Code = "GER" },
                new Country { Id = 88, Name = "Ghana", Code = "GHA" },
                new Country { Id = 89, Name = "Gibraltar", Code = "GBZ" },
                new Country { Id = 90, Name = "Greece", Code = "GRE" },
                new Country { Id = 91, Name = "Greenland", Code = "GRL" },
                new Country { Id = 92, Name = "Grenada", Code = "GRN" },
                new Country { Id = 93, Name = "Guadeloupe", Code = "GLP" },
                new Country { Id = 94, Name = "Guam", Code = "GUM" },
                new Country { Id = 95, Name = "Guatemala", Code = "GUA" },
                new Country { Id = 96, Name = "Guernsey", Code = "GBG" },
                new Country { Id = 97, Name = "Guinea", Code = "GUI" },
                new Country { Id = 98, Name = "Guinea-Bissau", Code = "GNB" },
                new Country { Id = 99, Name = "Guyana", Code = "GUY" },
                new Country { Id = 100, Name = "Haiti", Code = "HAI" },
                new Country { Id = 101, Name = "Heard & McDonald Islands", Code = "" },
                new Country { Id = 102, Name = "Vatican City", Code = "VAT" },
                new Country { Id = 103, Name = "Honduras", Code = "HON" },
                new Country { Id = 104, Name = "Hungary", Code = "HUN" },
                new Country { Id = 105, Name = "Iceland", Code = "ISL" },
                new Country { Id = 106, Name = "India", Code = "IND" },
                new Country { Id = 107, Name = "Indonesia", Code = "IDN" },
                new Country { Id = 108, Name = "Iran", Code = "IRN" },
                new Country { Id = 109, Name = "Iraq", Code = "IRQ" },
                new Country { Id = 110, Name = "Ireland", Code = "IRL" },
                new Country { Id = 111, Name = "Isle of Man", Code = "GBM" },
                new Country { Id = 112, Name = "Israel", Code = "ISR" },
                new Country { Id = 113, Name = "Italy", Code = "ITA" },
                new Country { Id = 114, Name = "Jamaica", Code = "JAM" },
                new Country { Id = 115, Name = "Japan", Code = "JPN" },
                new Country { Id = 116, Name = "Jersey", Code = "GBJ" },
                new Country { Id = 117, Name = "Jordan", Code = "JOR" },
                new Country { Id = 118, Name = "Kazakhstan", Code = "KAZ" },
                new Country { Id = 119, Name = "Kenya", Code = "KEN" },
                new Country { Id = 120, Name = "Kiribati", Code = "KIR" },
                new Country { Id = 121, Name = "Kuwait", Code = "KUW" },
                new Country { Id = 122, Name = "Kyrgyzstan", Code = "KGZ" },
                new Country { Id = 123, Name = "Laos", Code = "LAO" },
                new Country { Id = 124, Name = "Latvia", Code = "LVA" },
                new Country { Id = 125, Name = "Lebanon", Code = "LIB" },
                new Country { Id = 126, Name = "Lesotho", Code = "LES" },
                new Country { Id = 127, Name = "Liberia", Code = "LBR" },
                new Country { Id = 128, Name = "Libya", Code = "LBY" },
                new Country { Id = 129, Name = "Liechtenstein", Code = "LIE" },
                new Country { Id = 130, Name = "Lithuania", Code = "LTU" },
                new Country { Id = 131, Name = "Luxembourg", Code = "LUX" },
                new Country { Id = 132, Name = "Madagascar", Code = "MAD" },
                new Country { Id = 133, Name = "Malawi", Code = "MWI" },
                new Country { Id = 134, Name = "Malaysia", Code = "MAS" },
                new Country { Id = 135, Name = "Maldives", Code = "MDV" },
                new Country { Id = 136, Name = "Mali", Code = "MLI" },
                new Country { Id = 137, Name = "Malta", Code = "MLT" },
                new Country { Id = 138, Name = "Marshall Islands", Code = "MHL" },
                new Country { Id = 139, Name = "Martinique", Code = "MTQ" },
                new Country { Id = 140, Name = "Mauritania", Code = "MTN" },
                new Country { Id = 141, Name = "Mauritius", Code = "MRI" },
                new Country { Id = 142, Name = "Mayotte", Code = "MYT" },
                new Country { Id = 143, Name = "Mexico", Code = "MEX" },
                new Country { Id = 144, Name = "Micronesia", Code = "FSM" },
                new Country { Id = 145, Name = "Monaco", Code = "MON" },
                new Country { Id = 146, Name = "Mongolia", Code = "MNG" },
                new Country { Id = 147, Name = "Montenegro", Code = "MNE" },
                new Country { Id = 148, Name = "Montserrat", Code = "MSR" },
                new Country { Id = 149, Name = "Morocco", Code = "MAR" },
                new Country { Id = 150, Name = "Mozambique", Code = "MOZ" },
                new Country { Id = 151, Name = "Myanmar", Code = "MYA" },
                new Country { Id = 152, Name = "Namibia", Code = "NAM" },
                new Country { Id = 153, Name = "Nauru", Code = "NRU" },
                new Country { Id = 154, Name = "Nepal", Code = "NEP" },
                new Country { Id = 155, Name = "Netherlands", Code = "NED", Flag = imageFileLoader.LoadImage("nl.png") },
                new Country { Id = 156, Name = "New Caledonia", Code = "NCL" },
                new Country { Id = 157, Name = "New Zealand", Code = "NZL" },
                new Country { Id = 158, Name = "Nicaragua", Code = "NCA" },
                new Country { Id = 159, Name = "Niger", Code = "NIG" },
                new Country { Id = 160, Name = "Nigeria", Code = "NGA" },
                new Country { Id = 161, Name = "Niue", Code = "NIU" },
                new Country { Id = 162, Name = "Norfolk Island", Code = "NFK" },
                new Country { Id = 163, Name = "Northern Mariana Islands", Code = "NMI" },
                new Country { Id = 164, Name = "Norway", Code = "NOR" },
                new Country { Id = 165, Name = "Oman", Code = "OMA" },
                new Country { Id = 166, Name = "Pakistan", Code = "PAK" },
                new Country { Id = 167, Name = "Palau", Code = "PLW" },
                new Country { Id = 168, Name = "Panama", Code = "PAN" },
                new Country { Id = 169, Name = "Papua New Guinea", Code = "PNG" },
                new Country { Id = 170, Name = "Paraguay", Code = "PAR" },
                new Country { Id = 171, Name = "Peru", Code = "PER" },
                new Country { Id = 172, Name = "Philippines", Code = "PHI" },
                new Country { Id = 173, Name = "Pitcairn Islands", Code = "PCN" },
                new Country { Id = 174, Name = "Poland", Code = "POL" },
                new Country { Id = 175, Name = "Portugal", Code = "POR" },
                new Country { Id = 176, Name = "Puerto Rico", Code = "PUR" },
                new Country { Id = 177, Name = "Qatar", Code = "QAT" },
                new Country { Id = 178, Name = "South Korea", Code = "KOR" },
                new Country { Id = 179, Name = "Moldova", Code = "MDA" },
                new Country { Id = 180, Name = "Romania", Code = "ROU" },
                new Country { Id = 181, Name = "Russia", Code = "RUS" },
                new Country { Id = 182, Name = "Rwanda", Code = "RWA" },
                new Country { Id = 183, Name = "Réunion", Code = "REU" },
                new Country { Id = 184, Name = "St. Barthélemy", Code = "" },
                new Country { Id = 185, Name = "St. Helena", Code = "SHN" },
                new Country { Id = 186, Name = "St. Kitts & Nevis", Code = "SKN" },
                new Country { Id = 187, Name = "St. Lucia", Code = "LCA" },
                new Country { Id = 188, Name = "St. Martin", Code = "" },
                new Country { Id = 189, Name = "St. Pierre & Miquelon", Code = "SPM" },
                new Country { Id = 190, Name = "St. Vincent & Grenadines", Code = "VIN" },
                new Country { Id = 191, Name = "Samoa", Code = "SAM" },
                new Country { Id = 192, Name = "San Marino", Code = "SMR" },
                new Country { Id = 193, Name = "São Tomé & Príncipe", Code = "STP" },
                new Country { Id = 194, Name = "Saudi Arabia", Code = "KSA" },
                new Country { Id = 195, Name = "Senegal", Code = "SEN" },
                new Country { Id = 196, Name = "Serbia", Code = "SRB" },
                new Country { Id = 197, Name = "Seychelles", Code = "SEY" },
                new Country { Id = 198, Name = "Sierra Leone", Code = "SLE" },
                new Country { Id = 199, Name = "Singapore", Code = "SIN" },
                new Country { Id = 200, Name = "Sint Maarten", Code = "" },
                new Country { Id = 201, Name = "Slovakia", Code = "SVK" },
                new Country { Id = 202, Name = "Slovenia", Code = "SVN" },
                new Country { Id = 203, Name = "Solomon Islands", Code = "SOL" },
                new Country { Id = 204, Name = "Somalia", Code = "SOM" },
                new Country { Id = 205, Name = "South Africa", Code = "RSA" },
                new Country { Id = 206, Name = "South Georgia & South Sandwich Islands", Code = "" },
                new Country { Id = 207, Name = "South Sudan", Code = "" },
                new Country { Id = 208, Name = "Spain", Code = "ESP" },
                new Country { Id = 209, Name = "Sri Lanka", Code = "SRI" },
                new Country { Id = 210, Name = "Palestine", Code = "PLE" },
                new Country { Id = 211, Name = "Sudan", Code = "SUD" },
                new Country { Id = 212, Name = "Suriname", Code = "SUR" },
                new Country { Id = 213, Name = "Svalbard & Jan Mayen", Code = "" },
                new Country { Id = 214, Name = "Swaziland", Code = "SWZ" },
                new Country { Id = 215, Name = "Sweden", Code = "SWE" },
                new Country { Id = 216, Name = "Switzerland", Code = "SUI" },
                new Country { Id = 217, Name = "Syria", Code = "SYR" },
                new Country { Id = 218, Name = "Tajikistan", Code = "TJK" },
                new Country { Id = 219, Name = "Thailand", Code = "THA" },
                new Country { Id = 220, Name = "Macedonia", Code = "MKD" },
                new Country { Id = 221, Name = "Timor-Leste", Code = "TLS" },
                new Country { Id = 222, Name = "Togo", Code = "TOG" },
                new Country { Id = 223, Name = "Tokelau", Code = "TKL" },
                new Country { Id = 224, Name = "Tonga", Code = "TGA" },
                new Country { Id = 225, Name = "Trinidad & Tobago", Code = "TRI" },
                new Country { Id = 226, Name = "Tunisia", Code = "TUN" },
                new Country { Id = 227, Name = "Turkey", Code = "TUR" },
                new Country { Id = 228, Name = "Turkmenistan", Code = "TKM" },
                new Country { Id = 229, Name = "Turks & Caicos Islands", Code = "TCA" },
                new Country { Id = 230, Name = "Tuvalu", Code = "TUV" },
                new Country { Id = 231, Name = "Uganda", Code = "UGA" },
                new Country { Id = 232, Name = "Ukraine", Code = "UKR" },
                new Country { Id = 233, Name = "United Arab Emirates", Code = "UAE" },
                new Country { Id = 234, Name = "England", Code = "ENG" },
                new Country { Id = 235, Name = "Northern Ireland", Code = "NIR" },
                new Country { Id = 236, Name = "Scotland", Code = "SCO" },
                new Country { Id = 237, Name = "Wales", Code = "WAL" },
                new Country { Id = 238, Name = "Tanzania", Code = "TAN" },
                new Country { Id = 239, Name = "U.S. Outlying Islands", Code = "" },
                new Country { Id = 240, Name = "U.S. Virgin Islands", Code = "VIR" },
                new Country { Id = 241, Name = "US", Code = "USA" },
                new Country { Id = 242, Name = "Uruguay", Code = "URU" },
                new Country { Id = 243, Name = "Uzbekistan", Code = "UZB" },
                new Country { Id = 244, Name = "Vanuatu", Code = "VAN" },
                new Country { Id = 245, Name = "Venezuela", Code = "VEN" },
                new Country { Id = 246, Name = "Vietnam", Code = "VIE" },
                new Country { Id = 247, Name = "Wallis & Futuna", Code = "WLF" },
                new Country { Id = 248, Name = "Western Sahara", Code = "SAH" },
                new Country { Id = 249, Name = "Yemen", Code = "YEM" },
                new Country { Id = 250, Name = "Zambia", Code = "ZAM" },
                new Country { Id = 251, Name = "Zimbabwe", Code = "ZIM" },
                new Country { Id = 252, Name = "Åland Islands", Code = "ALD" }
            };
        }
    }
}